export const GET_PURCHASE_SUCCESS = 'GET_PURCHASE_SUCCESS'
export const GET_PURCHASE_ERROR = 'GET_PURCHASE_ERROR'
export const GET_PURCHASE_CONTRACT_SUCCESS = 'GET_PURCHASE_CONTRACT_SUCCESS'
export const GET_PURCHASE_CONTRACT_ERROR = 'GET_PURCHASE_CONTRACT_ERROR'